export const SET_QUERY = 'SET_QUERY';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const FETCH_SEARCH_RESULTS_START = 'FETCH_SEARCH_RESULTS_START';
export const FETCH_SEARCH_RESULTS_FAIL = 'FETCH_SEARCH_RESULTS_FAIL';
