// Search Results
export const FETCH_SEARCH_RESULTS_START = 'FETCH_SEARCH_RESULTS_START';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const FETCH_SEARCH_RESULTS_FAIL = 'FETCH_SEARCH_RESULTS_FAIL';

// Product Detail
export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START';
export const SET_PRODUCT = 'SET_PRODUCT';
export const FETCH_PRODUCT_FAIL = 'FETCH_PRODUCT_FAIL';
